{% set name = "classy_vision" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5753514981306dfe091b43742925b39b27f41e891ee112241975f9a781ad5549

build:
  number: 0
  skip: True  # [py<36 or not linux64]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - pytorch >=1.3.1
    - torchvision >=0.4.2
    # NOTE: pillow can be removed once the torchvision version is upped
    - pillow ==6.2.1

test:
  imports:
    - classy_vision
    - classy_vision.dataset
    - classy_vision.heads
    - classy_vision.hooks
    - classy_vision.losses
    - classy_vision.meters
    - classy_vision.models
    - classy_vision.optim
    - classy_vision.tasks
    - classy_vision.trainer
  commands:
    - classy-project test_project

about:
  home: https://classyvision.ai
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "An end-to-end PyTorch framework for image and video classification"
  doc_url: https://classyvision.ai/
  dev_url: https://github.com/facebookresearch/ClassyVision/

extra:
  recipe-maintainers:
    - mannatsingh
    - vreis
